-- =====================================================================
-- Miziki social layer — Supabase (Postgres) migration
--
-- Principles
--   * Metadata only. No audio, filenames or file paths ever stored.
--   * Player/library stay on-device; this is a published *view* of it.
--   * Default profile visibility: friends (accepted followers only).
--   * "friends" = accepted followers (one-way follow, approved by the
--     followed user unless their profile is public).
--   * Feed events are generated by triggers (not client-inserted), so
--     they can't be spoofed and always respect privacy.
--   * verified_stats is client-attested (the DB can't prove a listen).
--
-- Run in the Supabase SQL editor, or as a migration.
-- =====================================================================

-- ---------- types ----------------------------------------------------
create type public.visibility_level as enum ('private', 'friends', 'public');
create type public.follow_status    as enum ('pending', 'accepted');
create type public.feed_event_type  as enum ('added', 'pinned', 'review', 'unlock');

-- ---------- tables ---------------------------------------------------
create table public.profiles (
  id           uuid primary key references auth.users(id) on delete cascade,
  handle       text not null unique check (handle ~ '^[a-z0-9_]{3,24}$'),
  display_name text check (char_length(display_name) <= 50),
  bio          text check (char_length(bio) <= 280),
  avatar_url   text,
  visibility   public.visibility_level not null default 'friends',
  created_at   timestamptz not null default now()
);

create table public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followee_id uuid not null references public.profiles(id) on delete cascade,
  status      public.follow_status not null default 'pending',
  created_at  timestamptz not null default now(),
  primary key (follower_id, followee_id),
  check (follower_id <> followee_id)
);

create table public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

-- Shared album catalog. release_key = MusicBrainz release-group ID once
-- matching exists; until then a client-computed hash of normalized
-- artist|album|year. mbid is filled in later by the matching step.
create table public.releases (
  id          uuid primary key default gen_random_uuid(),
  release_key text not null unique check (char_length(release_key) between 8 and 64),
  title       text not null check (char_length(title) between 1 and 200),
  artist      text not null check (char_length(artist) between 1 and 200),
  year        smallint check (year between 1860 and 2200),
  mbid        uuid,
  created_at  timestamptz not null default now()
);

create table public.crate_items (
  user_id      uuid not null references public.profiles(id) on delete cascade,
  release_id   uuid not null references public.releases(id) on delete restrict,
  added_at     timestamptz not null default now(),
  quality_tier smallint check (quality_tier between 1 and 3),
  rating       smallint check (rating between 1 and 5),
  sleeve_note  text check (char_length(sleeve_note) <= 140),
  pin_rank     smallint check (pin_rank between 1 and 8),
  visibility   public.visibility_level,          -- null = inherit profile
  updated_at   timestamptz not null default now(),
  primary key (user_id, release_id),
  -- deferrable so pins can be reordered inside one transaction
  unique (user_id, pin_rank) deferrable initially deferred
);

-- Client-attested listening stats ("verified" = measured by the player).
create table public.verified_stats (
  user_id             uuid not null references public.profiles(id) on delete cascade,
  release_id          uuid not null references public.releases(id) on delete cascade,
  full_album_sessions integer not null default 0 check (full_album_sessions >= 0),
  unlocked_variant    text check (char_length(unlocked_variant) <= 60),
  last_session_at     timestamptz,
  primary key (user_id, release_id)
);

-- One row per user; row existing = sharing. Expires on its own.
create table public.now_spinning (
  user_id     uuid primary key references public.profiles(id) on delete cascade,
  release_id  uuid not null references public.releases(id) on delete cascade,
  track_title text check (char_length(track_title) <= 200),
  started_at  timestamptz not null default now(),
  expires_at  timestamptz not null default (now() + interval '10 minutes')
);

create table public.digging_list (
  user_id        uuid not null references public.profiles(id) on delete cascade,
  release_id     uuid not null references public.releases(id) on delete cascade,
  source_user_id uuid references public.profiles(id) on delete set null,
  added_at       timestamptz not null default now(),
  primary key (user_id, release_id)
);

create table public.feed_events (
  id         bigint generated always as identity primary key,
  actor_id   uuid not null references public.profiles(id) on delete cascade,
  type       public.feed_event_type not null,
  release_id uuid references public.releases(id) on delete cascade,
  payload    jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.reports (
  id             bigint generated always as identity primary key,
  reporter_id    uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  release_id     uuid references public.releases(id) on delete set null,
  reason         text not null check (char_length(reason) between 1 and 500),
  status         text not null default 'open',
  created_at     timestamptz not null default now()
);

-- ---------- indexes --------------------------------------------------
create index crate_items_user_added_idx on public.crate_items (user_id, added_at desc);
create index crate_items_release_idx    on public.crate_items (release_id);
create index follows_followee_idx       on public.follows (followee_id, status);
create index feed_events_actor_idx      on public.feed_events (actor_id, created_at desc);
create index feed_events_created_idx    on public.feed_events (created_at desc);
create index digging_list_user_idx      on public.digging_list (user_id, added_at desc);

-- ---------- helper functions ----------------------------------------
create function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  NEW.updated_at := now();
  return NEW;
end $$;

create function public.is_blocked_between(a uuid, b uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.blocks
    where (blocker_id = a and blocked_id = b)
       or (blocker_id = b and blocked_id = a)
  );
$$;

-- An item can be more private than the profile, never less.
create function public.effective_visibility(p_user uuid, p_item public.visibility_level)
returns public.visibility_level language sql stable security definer set search_path = public as $$
  select least(p.visibility, coalesce(p_item, p.visibility))
  from public.profiles p where p.id = p_user;
$$;

create function public.item_visibility(p_user uuid, p_release uuid)
returns public.visibility_level language sql stable security definer set search_path = public as $$
  select visibility from public.crate_items
  where user_id = p_user and release_id = p_release;
$$;

-- Central privacy check used by every read policy.
create function public.can_view(p_owner uuid, p_item public.visibility_level default null)
returns boolean language plpgsql stable security definer set search_path = public as $$
declare
  viewer uuid := auth.uid();
  eff    public.visibility_level;
begin
  if viewer is not null and viewer = p_owner then
    return true;
  end if;

  eff := public.effective_visibility(p_owner, p_item);
  if eff is null or eff = 'private' then
    return false;
  end if;

  if viewer is not null and public.is_blocked_between(viewer, p_owner) then
    return false;
  end if;

  if eff = 'public' then
    return viewer is not null;   -- signed-in users only
  end if;

  -- friends: accepted followers only
  return viewer is not null and exists (
    select 1 from public.follows f
    where f.follower_id = viewer and f.followee_id = p_owner and f.status = 'accepted'
  );
end $$;

-- ---------- triggers: housekeeping ----------------------------------
create trigger crate_items_touch
  before update on public.crate_items
  for each row execute function public.touch_updated_at();

-- Follow status is server-decided: auto-accept public profiles, else pending.
create function public.follows_before_insert()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if public.is_blocked_between(NEW.follower_id, NEW.followee_id) then
    raise exception 'cannot follow this user';
  end if;
  NEW.status := case
    when (select visibility from public.profiles where id = NEW.followee_id) = 'public'
      then 'accepted'::public.follow_status
    else 'pending'::public.follow_status
  end;
  return NEW;
end $$;

create trigger follows_before_insert
  before insert on public.follows
  for each row execute function public.follows_before_insert();

-- Blocking removes any follow relationship in both directions.
create function public.blocks_after_insert()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  delete from public.follows
  where (follower_id = NEW.blocker_id and followee_id = NEW.blocked_id)
     or (follower_id = NEW.blocked_id and followee_id = NEW.blocker_id);
  return NEW;
end $$;

create trigger blocks_after_insert
  after insert on public.blocks
  for each row execute function public.blocks_after_insert();

-- ---------- triggers: feed events -----------------------------------
create function public.crate_items_emit_events()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  eff        public.visibility_level;
  is_new     boolean := (TG_OP = 'INSERT');
  old_pin    smallint;
  old_rating smallint;
  old_note   text;
  old_vis    public.visibility_level;
  recent_id  bigint;
  vis_changed boolean := false;
begin
  if TG_OP = 'UPDATE' then
    old_pin := OLD.pin_rank;
    old_rating := OLD.rating;
    old_note := OLD.sleeve_note;
    old_vis := OLD.visibility;
    vis_changed := NEW.visibility is distinct from OLD.visibility;
  end if;

  eff := public.effective_visibility(NEW.user_id, NEW.visibility);

  -- Private items leave no trace in the feed.
  if eff is null or eff = 'private' then
    delete from public.feed_events
    where actor_id = NEW.user_id and release_id = NEW.release_id
      and type in ('pinned', 'review');
    return NEW;
  end if;

  -- added: collapse bursts (imports) into one event per 15 minutes
  if is_new then
    select id into recent_id from public.feed_events
    where actor_id = NEW.user_id and type = 'added'
      and created_at > now() - interval '15 minutes'
    order by created_at desc limit 1;

    if recent_id is not null then
      update public.feed_events
      set payload = jsonb_set(
            payload, '{count}',
            to_jsonb(coalesce((payload->>'count')::int, 1) + 1)),
          created_at = now()
      where id = recent_id;
    else
      insert into public.feed_events (actor_id, type, release_id, payload)
      values (NEW.user_id, 'added', NEW.release_id, '{"count": 1}'::jsonb);
    end if;
  end if;

  -- pinned
  if NEW.pin_rank is null then
    delete from public.feed_events
    where actor_id = NEW.user_id and release_id = NEW.release_id and type = 'pinned';
  elsif is_new or old_pin is null or vis_changed then
    delete from public.feed_events
    where actor_id = NEW.user_id and release_id = NEW.release_id and type = 'pinned';
    insert into public.feed_events (actor_id, type, release_id, payload)
    values (NEW.user_id, 'pinned', NEW.release_id, '{}'::jsonb);
  end if;

  -- review (rating and/or sleeve note): one live event per record
  if NEW.rating is null and NEW.sleeve_note is null then
    delete from public.feed_events
    where actor_id = NEW.user_id and release_id = NEW.release_id and type = 'review';
  elsif is_new
     or NEW.rating is distinct from old_rating
     or NEW.sleeve_note is distinct from old_note
     or vis_changed then
    delete from public.feed_events
    where actor_id = NEW.user_id and release_id = NEW.release_id and type = 'review';
    insert into public.feed_events (actor_id, type, release_id, payload)
    values (NEW.user_id, 'review', NEW.release_id,
            jsonb_build_object('rating', NEW.rating, 'note', NEW.sleeve_note));
  end if;

  return NEW;
end $$;

create trigger crate_items_emit_events
  after insert or update on public.crate_items
  for each row execute function public.crate_items_emit_events();

create function public.crate_items_after_delete()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  delete from public.feed_events
  where actor_id = OLD.user_id and release_id = OLD.release_id
    and type in ('pinned', 'review');
  return OLD;
end $$;

create trigger crate_items_after_delete
  after delete on public.crate_items
  for each row execute function public.crate_items_after_delete();

create function public.verified_stats_emit_events()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  eff public.visibility_level;
  changed boolean;
begin
  if NEW.unlocked_variant is null then
    return NEW;
  end if;
  if TG_OP = 'UPDATE' then
    changed := NEW.unlocked_variant is distinct from OLD.unlocked_variant;
  else
    changed := true;
  end if;
  if not changed then
    return NEW;
  end if;

  eff := public.effective_visibility(
           NEW.user_id, public.item_visibility(NEW.user_id, NEW.release_id));
  if eff is null or eff = 'private' then
    return NEW;
  end if;

  insert into public.feed_events (actor_id, type, release_id, payload)
  values (NEW.user_id, 'unlock', NEW.release_id,
          jsonb_build_object('variant', NEW.unlocked_variant));
  return NEW;
end $$;

create trigger verified_stats_emit_events
  after insert or update on public.verified_stats
  for each row execute function public.verified_stats_emit_events();

-- Trigger functions are not meant to be called directly.
revoke execute on function
  public.follows_before_insert(), public.blocks_after_insert(),
  public.crate_items_emit_events(), public.crate_items_after_delete(),
  public.verified_stats_emit_events()
from public, anon, authenticated;

-- ---------- row level security --------------------------------------
alter table public.profiles       enable row level security;
alter table public.follows        enable row level security;
alter table public.blocks         enable row level security;
alter table public.releases       enable row level security;
alter table public.crate_items    enable row level security;
alter table public.verified_stats enable row level security;
alter table public.now_spinning   enable row level security;
alter table public.digging_list   enable row level security;
alter table public.feed_events    enable row level security;
alter table public.reports        enable row level security;

-- profiles: basics are findable by handle (needed to send a follow
-- request) unless a block exists. Contents of a crate are NOT here.
create policy profiles_select on public.profiles for select to authenticated
  using (not public.is_blocked_between(auth.uid(), id));
create policy profiles_insert on public.profiles for insert to authenticated
  with check (id = auth.uid());
create policy profiles_update on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_delete on public.profiles for delete to authenticated
  using (id = auth.uid());

-- follows: only the two parties can see a relationship.
create policy follows_select on public.follows for select to authenticated
  using (follower_id = auth.uid() or followee_id = auth.uid());
create policy follows_insert on public.follows for insert to authenticated
  with check (follower_id = auth.uid());
create policy follows_update on public.follows for update to authenticated
  using (followee_id = auth.uid()) with check (followee_id = auth.uid());
create policy follows_delete on public.follows for delete to authenticated
  using (follower_id = auth.uid() or followee_id = auth.uid());

-- blocks: private to the blocker.
create policy blocks_select on public.blocks for select to authenticated
  using (blocker_id = auth.uid());
create policy blocks_insert on public.blocks for insert to authenticated
  with check (blocker_id = auth.uid());
create policy blocks_delete on public.blocks for delete to authenticated
  using (blocker_id = auth.uid());

-- releases: shared catalog, readable by all signed-in users, insert-only.
create policy releases_select on public.releases for select to authenticated
  using (true);
create policy releases_insert on public.releases for insert to authenticated
  with check (true);

-- crate_items
create policy crate_select on public.crate_items for select to authenticated
  using (public.can_view(user_id, visibility));
create policy crate_insert on public.crate_items for insert to authenticated
  with check (user_id = auth.uid());
create policy crate_update on public.crate_items for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy crate_delete on public.crate_items for delete to authenticated
  using (user_id = auth.uid());

-- verified_stats
create policy stats_select on public.verified_stats for select to authenticated
  using (public.can_view(user_id, public.item_visibility(user_id, release_id)));
create policy stats_insert on public.verified_stats for insert to authenticated
  with check (user_id = auth.uid());
create policy stats_update on public.verified_stats for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy stats_delete on public.verified_stats for delete to authenticated
  using (user_id = auth.uid());

-- now_spinning: only live rows; cannot publish a private record.
create policy spinning_select on public.now_spinning for select to authenticated
  using (expires_at > now() and public.can_view(user_id, null));
create policy spinning_insert on public.now_spinning for insert to authenticated
  with check (
    user_id = auth.uid()
    and public.effective_visibility(
          auth.uid(), public.item_visibility(auth.uid(), release_id)) <> 'private'
  );
create policy spinning_update on public.now_spinning for update to authenticated
  using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    and public.effective_visibility(
          auth.uid(), public.item_visibility(auth.uid(), release_id)) <> 'private'
  );
create policy spinning_delete on public.now_spinning for delete to authenticated
  using (user_id = auth.uid());

-- digging_list: private to owner.
create policy digging_all on public.digging_list for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- feed_events: read-only for clients (written only by triggers).
create policy feed_select on public.feed_events for select to authenticated
  using (public.can_view(actor_id, null));

-- reports: write-only for users (review via service role / dashboard).
create policy reports_insert on public.reports for insert to authenticated
  with check (reporter_id = auth.uid());
create policy reports_select on public.reports for select to authenticated
  using (reporter_id = auth.uid());

-- ---------- grants ---------------------------------------------------
revoke all on public.profiles, public.follows, public.blocks, public.releases,
              public.crate_items, public.verified_stats, public.now_spinning,
              public.digging_list, public.feed_events, public.reports
  from anon;

-- Column-level write limits: clients can't rewrite keys or timestamps.
revoke update on public.profiles from authenticated;
grant  update (handle, display_name, bio, avatar_url, visibility)
  on public.profiles to authenticated;

revoke update on public.follows from authenticated;
grant  update (status) on public.follows to authenticated;

revoke update on public.crate_items from authenticated;
grant  update (quality_tier, rating, sleeve_note, pin_rank, visibility)
  on public.crate_items to authenticated;

revoke update on public.verified_stats from authenticated;
grant  update (full_album_sessions, unlocked_variant, last_session_at)
  on public.verified_stats to authenticated;

revoke update, delete on public.releases from authenticated;
revoke insert, update, delete on public.feed_events from authenticated;
revoke update, delete on public.reports from authenticated;

-- ---------- RPCs -----------------------------------------------------
-- Home feed: own + accepted follows, newest first, paged by timestamp.
create function public.home_feed(p_limit int default 50, p_before timestamptz default now())
returns setof public.feed_events
language sql stable security invoker set search_path = public as $$
  select e.* from public.feed_events e
  where e.created_at < p_before
    and (
      e.actor_id = auth.uid()
      or exists (
        select 1 from public.follows f
        where f.follower_id = auth.uid()
          and f.followee_id = e.actor_id
          and f.status = 'accepted'
      )
    )
  order by e.created_at desc
  limit least(greatest(p_limit, 1), 100);
$$;

-- Records you and another user both have (only what RLS lets you see).
create function public.records_in_common(p_other uuid)
returns table (release_id uuid, title text, artist text, year smallint)
language sql stable security invoker set search_path = public as $$
  select r.id, r.title, r.artist, r.year
  from public.crate_items mine
  join public.crate_items theirs
    on theirs.release_id = mine.release_id and theirs.user_id = p_other
  join public.releases r on r.id = mine.release_id
  where mine.user_id = auth.uid()
  order by r.artist, r.year, r.title;
$$;

-- ---------- realtime (now spinning) ----------------------------------
do $$
begin
  alter publication supabase_realtime add table public.now_spinning;
exception when undefined_object then
  null;  -- publication not present outside Supabase
end $$;
